'use client';
import { useEffect, useState } from 'react';

type Subscription = { id: string; deviceLabel: string | null; active: boolean; createdAt: string; revokedAt: string | null };
type Preference = { pushEnabled: boolean; deliveryMode: 'IMMEDIATE' | 'DIGEST'; quietHoursStart: string | null; quietHoursEnd: string | null };
export function NotificationDeviceSettings() {
  const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [preference, setPreference] = useState<Preference>({ pushEnabled: true, deliveryMode: 'IMMEDIATE', quietHoursStart: null, quietHoursEnd: null }); const [message, setMessage] = useState('');
  const load = () => Promise.all([fetch('/api/notifications/subscriptions').then((r) => r.json()), fetch('/api/notifications/preferences').then((r) => r.json())]).then(([devices, settings]) => { setSubscriptions(devices.subscriptions || []); if (settings.preference) setPreference(settings.preference); }).catch(() => setMessage('Unable to load notification settings.'));
  useEffect(() => { load(); }, []);
  const save = async () => { const response = await fetch('/api/notifications/preferences', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(preference) }); setMessage(response.ok ? 'Notification preferences saved.' : 'Unable to save notification preferences.'); };
  const revoke = async (id: string) => { const response = await fetch(`/api/notifications/subscriptions?id=${id}`, { method: 'DELETE' }); setMessage(response.ok ? 'Device subscription revoked.' : 'Unable to revoke this device.'); load(); };
  return <section className="space-y-4"><div><h2 className="text-lg font-black">Notification settings</h2><p className="text-sm text-slate-500">Manage quiet hours and view devices registered for alerts.</p></div><div className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={preference.pushEnabled} onChange={(event) => setPreference({ ...preference, pushEnabled: event.target.checked })} /> Enable browser push</label><label className="text-sm">Delivery<select value={preference.deliveryMode} onChange={(event) => setPreference({ ...preference, deliveryMode: event.target.value as Preference['deliveryMode'] })} className="ml-2 rounded border p-1"><option value="IMMEDIATE">Immediate</option><option value="DIGEST">Digest</option></select></label><label className="text-sm">Quiet from<input type="time" value={preference.quietHoursStart || ''} onChange={(event) => setPreference({ ...preference, quietHoursStart: event.target.value || null })} className="ml-2 rounded border p-1" /></label><label className="text-sm">Quiet until<input type="time" value={preference.quietHoursEnd || ''} onChange={(event) => setPreference({ ...preference, quietHoursEnd: event.target.value || null })} className="ml-2 rounded border p-1" /></label><button onClick={save} className="rounded bg-slate-900 px-3 py-2 text-xs font-bold text-white">Save settings</button></div><div className="rounded-xl border bg-white p-4"><p className="font-black">Registered devices</p>{subscriptions.length ? subscriptions.map((item) => <div key={item.id} className="mt-2 flex items-center justify-between border-t pt-2 text-sm"><span>{item.deviceLabel || 'Unnamed browser'} · {item.active ? 'Active' : `Revoked ${new Date(item.revokedAt!).toLocaleDateString()}`}</span>{item.active && <button onClick={() => revoke(item.id)} className="text-xs font-bold text-red-700 underline">Revoke</button>}</div>) : <p className="mt-2 text-sm text-slate-500">No browser device is registered.</p>}</div>{message && <p className="text-sm text-slate-600">{message}</p>}</section>;
}
