/** Stable management labels mapped from operational statuses. */
export const MANAGEMENT_VEHICLE_STAGES = [
  'AWAITING_PLANT_ENTRY',
  'AT_PLANT_GATE',
  'PLANT_QA',
  'AWAITING_GROSS_WEIGHT',
  'AWAITING_UNLOADING',
  'UNLOADING',
  'AWAITING_TARE_WEIGHT',
  'AWAITING_PLANT_EXIT',
  'COMPLETED',
  'REJECTED_OR_EXITING',
  'UNKNOWN',
] as const;

export type ManagementVehicleStage = (typeof MANAGEMENT_VEHICLE_STAGES)[number];

const STATUS_TO_STAGE: Record<string, ManagementVehicleStage> = {
  DRAFT_DISPATCH: 'AWAITING_PLANT_ENTRY', DISPATCHED: 'AWAITING_PLANT_ENTRY', Dispatched: 'AWAITING_PLANT_ENTRY',
  TOKEN_ISSUED: 'AT_PLANT_GATE', PLANT_QA: 'PLANT_QA',
  READY_FOR_GROSS: 'AWAITING_GROSS_WEIGHT', GROSS_WEIGHED: 'AWAITING_UNLOADING', READY_FOR_UNLOADING: 'AWAITING_UNLOADING',
  UNLOADING: 'UNLOADING', UNLOADED: 'AWAITING_TARE_WEIGHT', READY_FOR_TARE: 'AWAITING_TARE_WEIGHT', TARE_WEIGHED: 'AWAITING_PLANT_EXIT',
  READY_FOR_GATE_EXIT: 'AWAITING_PLANT_EXIT', COMPLETED: 'COMPLETED', REJECTED: 'REJECTED_OR_EXITING', CANCELLED: 'REJECTED_OR_EXITING',
};

export function toManagementVehicleStage(status: string | null | undefined): ManagementVehicleStage {
  return status ? STATUS_TO_STAGE[status] || 'UNKNOWN' : 'UNKNOWN';
}
