import fs from 'fs';
import path from 'path';

const repoRoot = path.resolve(__dirname, '../..');

function loadEnvFile(filePath: string): void {
  if (!fs.existsSync(filePath)) return;
  const envContent = fs.readFileSync(filePath, 'utf8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const idx = trimmed.indexOf('=');
      if (idx > 0) {
        const key = trimmed.substring(0, idx).trim();
        let val = trimmed.substring(idx + 1).trim();
        if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
          val = val.substring(1, val.length - 1);
        }
        if (!process.env[key]) {
          process.env[key] = val;
        }
      }
    }
  }
}

export function initTestEnvironment(): void {
  // 1. Load main .env
  loadEnvFile(path.join(repoRoot, '.env'));
  if (process.env.DATABASE_URL) {
    process.env.DEV_DATABASE_URL = process.env.DATABASE_URL;
  }

  // 2. Load .env.test.local (generated by npm run test:db:setup)
  loadEnvFile(path.join(repoRoot, '.env.test.local'));

  // In test environment, point DATABASE_URL to TEST_DATABASE_URL so app routes use the isolated test DB
  if (process.env.TEST_DATABASE_URL) {
    process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  }
}


// Automatically initialize test environment when imported
initTestEnvironment();

